
            FROM jvsoest/base_fairmodels
            WORKDIR /app
            COPY ntcp_model_dysphalgia.json /app/model_parameters.json
            ENV MODULE_NAME=model_execution_default
            ENV CLASS_NAME=model_execution_linear_regression
            